version: "3.9"
services:
  api:
    build: ./services/api
    env_file: .env
    depends_on:
      - influxdb
      - redis
    ports:
      - "8000:8000"

  ingestion:
    build: ./services/ingestion
    env_file: .env
    depends_on:
      - mqtt-broker
      - influxdb

  frontend:
    build: ./services/frontend
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - api

  mqtt-broker:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports:
      - "1883:1883"

  influxdb:
    image: influxdb:2.7
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=hospital
      - DOCKER_INFLUXDB_INIT_BUCKET=metrics
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=dev-token
    volumes:
      - influx_data:/var/lib/influxdb2

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  stream-server:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    restart: unless-stopped
    ports:
      - "8554:8554"
      - "8889:8889"
    volumes:
      - ./infra/mediamtx/mediamtx.yml:/mediamtx.yml

  stream-gateway:
    build: ./services/stream-gateway
    env_file: .env
    ports:
      - "9000:9000"
    depends_on:
      - stream-server

  mock-sensor:
    build: ./services/mock-sensor
    environment:
      - INTERVAL=${MOCK_INTERVAL_SECONDS}
      - COUNT=${MOCK_DEVICE_COUNT}
      - BUILDING=${MOCK_BUILDING}
      - FLOOR=${MOCK_FLOOR}
      - MQTT_HOST=mqtt-broker
    depends_on:
      - mqtt-broker

  nginx:
    image: nginx:alpine
    depends_on:
      - api
      - frontend
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"

volumes:
  influx_data: